2024-08-27 22:43:38,035 INFO    MainThread:23828 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-08-27 22:43:38,035 INFO    MainThread:23828 [wandb_setup.py:_flush():76] Configure stats pid to 23828
2024-08-27 22:43:38,035 INFO    MainThread:23828 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Isara Liyanage\.config\wandb\settings
2024-08-27 22:43:38,035 INFO    MainThread:23828 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Isara Liyanage\Documents\GitHub\HealthBot_Plus\wandb\settings
2024-08-27 22:43:38,036 INFO    MainThread:23828 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-27 22:43:38,036 INFO    MainThread:23828 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'HealthBot Plus App\\backend\\app.py', 'program_abspath': 'c:\\Users\\Isara Liyanage\\Documents\\GitHub\\HealthBot_Plus\\HealthBot Plus App\\backend\\app.py', 'program': 'c:\\Users\\Isara Liyanage\\Documents\\GitHub\\HealthBot_Plus\\HealthBot Plus App\\backend\\app.py'}
2024-08-27 22:43:38,041 INFO    MainThread:23828 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-27 22:43:38,041 INFO    MainThread:23828 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-27 22:43:38,042 INFO    MainThread:23828 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\Isara Liyanage\Documents\GitHub\HealthBot_Plus\wandb\run-20240827_224338-ml58gm2k\logs\debug.log
2024-08-27 22:43:38,042 INFO    MainThread:23828 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\Isara Liyanage\Documents\GitHub\HealthBot_Plus\wandb\run-20240827_224338-ml58gm2k\logs\debug-internal.log
2024-08-27 22:43:38,042 INFO    MainThread:23828 [wandb_init.py:init():607] calling init triggers
2024-08-27 22:43:38,042 INFO    MainThread:23828 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-08-27 22:43:38,042 INFO    MainThread:23828 [wandb_init.py:init():657] starting backend
2024-08-27 22:43:38,042 INFO    MainThread:23828 [wandb_init.py:init():661] setting up manager
2024-08-27 22:43:38,047 INFO    MainThread:23828 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-08-27 22:43:38,051 INFO    MainThread:23828 [wandb_init.py:init():669] backend started and connected
2024-08-27 22:43:38,060 INFO    MainThread:23828 [wandb_init.py:init():764] updated telemetry
2024-08-27 22:43:38,111 INFO    MainThread:23828 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2024-08-27 22:43:39,557 ERROR   MainThread:23828 [wandb_init.py:init():823] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-08-27 22:43:39,557 ERROR   MainThread:23828 [wandb_init.py:init():1235] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Isara Liyanage\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1225, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\Isara Liyanage\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 829, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-08-27 22:43:41,772 WARNING MsgRouterThr:23828 [router.py:message_loop():77] message_loop has been closed
